services:
  chromeos:
    image: dockurr/chromeos
    container_name: chromeos
    environment:
      GPU: "N"
      VERSION: "stable"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./chromeos:/storage
    restart: always
    stop_grace_period: 2m
